name: flutter_ebook_app
description: A Flutter app for eBooks

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  epub_viewer: ^0.2.2
  flutter:
    sdk: flutter
  flutter_icons:
    git: https://github.com/jibiel/flutter-icons
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.8
  google_fonts: ^2.1.0
  objectdb: ^1.2.1+1
  path_provider: ^2.0.3
  permission_handler: ^8.1.6
  provider: ^6.0.0
  share: 2.0.4
  shared_preferences: ^2.0.7
  uuid: ^3.0.4
  xml2json: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
